src/apps/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path("", subjects, name="subjects"),
    path("dashboard/", dashboard, name="dashboard"),
    path("login/", login_view, name="login"),

    path("create-subject/", create_subject, name="add_subject"),
    path("subject/<int:pk>", subject_details, name="subject_details"),
    path("edit-subject/<int:pk>", edit_subject, name="edit_subject"),
    path("delete-subject/<int:pk>", delete_subject, name="delete_subject"),
    
    path("create-topic/<int:subject_pk>", create_topic, name="add_topic"),
    path("subject/<int:subject_pk>/topic/<int:topic_pk>", retrieve_topic, name="topic_details"),
    path("edit-topic/<int:topic_id>", edit_topic, name="edit_topic"),
    path("delete-topic/<int:topic_id>", delete_topic, name="delete_topic"),

]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  


urlpatterns = [
    path('admin-panel/', admin.site.urls, name="admin"),
    path("", include("apps.posts.urls", namespace="posts"), name="posts"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/posts/models.py
from django.db import models

class Subject(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    


class Topic(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='topics')
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):  
        return self.title

src/apps/posts/forms.py
from .models import Subject, Topic
from django import forms
from django.contrib.auth import authenticate

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['title', 'body']

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label="Username", required=True)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput, label="Password", required=True)

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("Invalid username or password.")
        return self.cleaned_data

src/apps/posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Subject, Topic
from .forms import SubjectForm, TopicForm, LoginForm
from django.contrib.auth import authenticate, login


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('posts:dashboard')
            else:
                form.add_error(None, "Invalid username or password.")
    else:
        form = LoginForm()

    context = {'form': form}
    return render(request, 'dashboard/login.html', context)

def subjects(request):
    subject_qs = Subject.objects.all().prefetch_related("topics")
    contexts = {
        "subjects": subject_qs
    }
    return render(request, "posts/subjects.html", contexts)

def dashboard(request):
    if request.user.is_authenticated:
        subject_list = Subject.objects.all()
        return render(request, "dashboard/home.html", {"subjects":subject_list})
    else:
        return redirect("posts:login")




def create_subject(request):
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:subjects')
    else:
        form = SubjectForm()
    context = {'form': form}
    return render(request, 'posts/create_subject.html', context)

def subject_details(request, pk):
    subject = Subject.objects.get(pk=pk)
    return render(request, "posts/subject_details.html", {"subject": subject})

def edit_subject(request, pk):
    try:
        subject = Subject.objects.get(pk=pk)
        if request.method == 'POST':
            form = SubjectForm(request.POST, instance=subject)
            if form.is_valid():
                form.save()
                return redirect('posts:subjects')
        else:
            form = SubjectForm(instance=subject)
        context = {"subject":subject, 'form': form}
        return render(request, 'posts/edit_subject.html', context)
    except Subject.DoesNotExist:
        return HttpResponse("Id raqam xato kiritlgan !")
    except Exception as e:
        return HttpResponse(e.args)
    
def delete_subject(request, pk):
    try:
        subject = Subject.objects.get(pk=pk)
        subject.delete()
        return redirect('posts:subjects')
    except Subject.DoesNotExist:
        return HttpResponse("Id raqam xato kiritlgan !")
    except Exception as e:
        return HttpResponse(e.args)
    


def create_topic(request, subject_pk):
    try:
        if request.method == 'POST':
            form = TopicForm(request.POST)
            if form.is_valid():
                topic_kwargs = {
                    "subject_id": subject_pk,
                    "title": form.cleaned_data['title'],
                    "body": form.cleaned_data['body']
                }
                Topic.objects.create(**topic_kwargs)
                return redirect('posts:subjects')
        else:
            form = TopicForm(initial={'subject': subject_pk})
            return render(request, 'posts/create_topic.html', {"subject_id": subject_pk, "form": form})
    except Exception as e:
        # Implement proper error handling here
        print(f"Error creating topic: {e}")
        return render(request, 'posts/create_topic.html',{'error': 'An error occurred while creating the topic.'})

def retrieve_topic(request, subject_pk, topic_pk):
    try:
        topic = Topic.objects.get(id=topic_pk)
        return render(request, "posts/topic_details.html", {"topic":topic})
    
    except Topic.DoesNotExist:
        return HttpResponse("Id raqam xato kiritlgan !")
    except Exception as e:
        return HttpResponse(e.args)
    
def edit_topic(request, topic_id):
    try:
        topic = Topic.objects.get(id=topic_id)
        if request.method == 'POST':
            form = TopicForm(request.POST, instance=topic)
            if form.is_valid():
                form.save()
                return redirect('posts:subjects')
        else:
            form = TopicForm(instance=topic)
        context = {"topic":topic, 'form': form}
        return render(request, 'posts/edit_topic.html', context)
    except Topic.DoesNotExist:
        return HttpResponse("Id raqam xato kiritlgan !")
    except Exception as e:
        return HttpResponse(e.args)

def delete_topic(request, topic_id):
    try:
        topic = Topic.objects.get(id=topic_id)
        topic.delete()
        return redirect('posts:subjects')
    except Topic.DoesNotExist:
        return HttpResponse("Id raqam xato kiritlgan !")
    except Exception as e:
        return HttpResponse(e.args)

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    <nav>
        <a class="btn atd" href="{% url 'posts:dashboard' %}">Dashboard</a>
    </nav>
    {% block content %}
    {% endblock content %}
</body>
</html>

src/templates/dashboard/home.html
{% extends "base.html" %}

{% block title %}
Dashboard
{% endblock title %}

{% block content %}

<div class="main">
    <h1>Subjects</h1>
    {% for subject in subjects %}
        <h3>
            <a href="{% url 'posts:subject_details' subject.id %}" class="atd white">
                {{ subject.name }}
            </a>
        </h3>   
    {% endfor %}
    <a href="{% url 'posts:add_subject' %}" class="btn atd">Add subject</a>
    <a href="{% url 'posts:subjects' %}" class="btn atd">Home</a>
</div>
{% endblock content %}

src/templates/dashboard/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock title %}

{% block content %}

    <div class="main">
        <form action="." method="post" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Login</button>
        </form>
    </div>

{% endblock content %}

src/templates/posts/create_subject.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Add subject
{% endblock title %}


{% block content %}

    <div class="main">
        <form action="." method="post" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Save</button>
            <a href="{{ request.META.HTTP_REFERER }}" class="btn atd">
                <img src="{% static 'back-icon.svg' %}" class="icon">
                back
            </a>
        </form>
    </div>
<!-- {% url 'posts:subjects' %} -->
{% endblock content %}

src/templates/posts/create_topic.html
{% extends "base.html" %}
{% load static %}

{% block title %}
create topic
{% endblock title %}

{% block content %}
<div class="main">
    <h2>Create topic</h2>
    {% if error %}
      <p class="error">{{ error }}</p>
    {% endif %}
    <form action="{% url 'posts:add_topic' subject_id %}" method="post" class="form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn atd">Save</button>
      <a href="{{ request.META.HTTP_REFERER }}" class="btn atd">
        <img src="{% static 'back-icon.svg' %}" class="icon">
        back
      </a>
    </form>
  </div>

{% endblock content %}

src/templates/posts/edit_subject.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Edit subject
{% endblock title %}

{% block content %}
    <div class='main'>
        <form action="{% url 'posts:edit_subject' subject.id %}" method="post" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Save</button>
            <a href="{{ request.META.HTTP_REFERER }}" class="btn atd"><img src="{% static 'back-icon.svg' %}" class="icon">back</a>
        </form>
    </div>
{% endblock content %}

src/templates/posts/edit_topic.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Edit topic
{% endblock title %}

{% block content %}
    <div class="main">
        <h2>Edit topic</h2>
        <form action="{% url 'posts:edit_topic' topic.id %}" method="post" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Save</button>
            <a href="{{ request.META.HTTP_REFERER }}" class="btn atd">
                <img src="{% static 'back-icon.svg' %}" class="icon">
                back
            </a>
        </form>
    </div>

{% endblock content %}

src/templates/posts/subject_details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{subject.name}}
{% endblock title %}

{% block content %}

    <div class="main">
        <h2>Name: {{ subject.name }}</h2>
        <a href="{% url 'posts:edit_subject' subject.id %}" class="btn atd tooltip">
            <span class="tooltiptext">Edit subject</span>
            <img src="{% static 'edit-outline.svg' %}" alt="" class='icon'>
        </a>
        <a href="{% url 'posts:delete_subject' subject.id %}" class="btn-danger atd tooltip">
            <img src="{% static 'delete-icon.svg' %}" alt="" class='icon'>
            <span class="tooltiptext">Delete subject</span>
        </a>

        {% if subject.topics.exists %}
            <h3>Topics in this subject:</h3>
            {% for topic in subject.topics.all %}
                <div class="flex-start">
                    <a href="{% url 'posts:topic_details' subject.id topic.id %}" class="atd white block">
                        {{ topic.title }}
                    </a>
                    <div>
                        <a href="{% url 'posts:edit_topic' topic.id %}" class="atd tooltip">
                            <span class="tooltiptext">Edit topic</span>
                            <img src="{% static 'edit-outline.svg' %}" alt="" class="icon">
                        </a>
                        <a href="{% url 'posts:delete_topic' topic.id %}" class="atd tooltip">
                            <span class="tooltiptext">Delete topic</span>
                            <img src="{% static 'delete-icon.svg' %}" alt="" class="icon">
                        </a>
                    </div>
                </div>        
            {% endfor %}
        
        {% else %}
            <h3>There is no any topic in this subject !</h3>
        {% endif %}
        <br>
        <a href="{% url 'posts:add_topic' subject.id %}" class="btn atd">
            Add topic
        </a>
        <a href="{% url 'posts:dashboard' %}" class="btn atd">
            <img src="{% static 'back-icon.svg' %}" class="icon">
            back
        </a>
    </div>

{% endblock content %}

src/templates/posts/subjects.html
{% extends "base.html" %}

{% block title %}
    Chavo   
{% endblock title %}

{% block content %}
    <div class="main">
        <div class="grid-c2">
            {% for subject in subjects %}
            <div class="subject">
                <h2 class="white">{{ subject.name }}</h2>
                {% for topic in subject.topics.all %}
                    <a href="{% url 'posts:topic_details' subject.id topic.id %}" rel="noopener noreferrer" class="atd white">
                        {{ topic.title }}
                    </a>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        <div class="grid-c1">
        </div>
    </div>
{% endblock content %}

src/templates/posts/topic_details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ topic.title }}
{% endblock title %}

{% block content %}

    <div class="detail">
        <h2>{{ topic.title }}</h2>
        <p>{{ topic.body }}</p><br>
        
        <a href="{% url 'posts:subjects' %}" class="btn atd">
            <img src="{% static 'back-icon.svg' %}" class="icon">
            back
        </a>
    </div>

{% endblock content %}